"""empty message

Revision ID: bc3f926a58d1
Revises: 
Create Date: 2024-01-31 21:08:37.393108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3f926a58d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('last_activity',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_activity',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_on',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
